// Generated by CoffeeScript 1.6.3
var getDataFor, page, renderChart;

page = require('webpage').create();

renderChart = function(data, id) {
  page.evaluate(function(rawData) {
    return drawChart(rawData);
  }, data);
  if (id < 10) {
    id = '0' + id;
  }
  page.render('render/img' + id + '.png');
  return console.log('Rendered \'img' + id + '.png\'');
};

page.onLoadFinished = function(status) {
  var data, x, _i, _ref;
  if (status === 'success') {
    data = getDataFor('gauge');
    for (x = _i = 0, _ref = data.length; _i < _ref; x = _i += 1) {
      renderChart(data[x], x);
    }
    return phantom.exit();
  } else {
    console.log('Connection failed.');
    return phantom.exit();
  }
};

page.onConsoleMessage = function(msg) {
  return console.log(msg);
};

page.viewportSize = {
  width: 400,
  height: 200
};

page.open('chart-markdown/gauge.html');

getDataFor = function(type) {
  if (type === 'gauge') {
    return [[['Label', 'Value'], ['Foo', 1], ['Bar', 1], ['Baz', 1]], [['Label', 'Value'], ['fg', 200], ['sdfsdg', 51], ['Badsdgz', 87]], [['Label', 'Value'], ['Fodsfo', 65], ['Baddr', 45], ['Badfdsfz', 56]], [['Label', 'Value'], ['Fosdfo', 78], ['Badsfr', 100], ['Bdsfz', 54]]];
  }
};
