// Generated by CoffeeScript 1.6.3
var data, id, imgHeight, imgWidth, page, renderChart, system, type, typeIsArray;

page = require('webpage').create();

system = require('system');

typeIsArray = Array.isArray || function(value) {
  return {}.toString.call(value) === '[object Array]';
};

if (system.args.length === 6) {
  id = system.args[1];
  data = system.args[2];
  type = system.args[3];
  imgWidth = system.args[4];
  imgHeight = system.args[5];
} else {
  console.log('Usage: render.js id data type imgWidth imgHeight');
  phantom.exit();
}

console.log('--- Starting Image Generation ---');

console.log('-+ Chart Type: ' + type);

console.log('-+ Image Width: ' + imgWidth);

console.log('-+ Image Height: ' + imgHeight);

console.log('---------------------------------');

renderChart = function(data, id) {
  page.evaluate(function(rawData) {
    window.rawData = rawData;
    return drawChart(rawData);
  }, data);
  if (id < 10) {
    id = '0' + id;
  }
  page.render('render/img' + id + '.png');
  return console.log('Rendered \'img' + id + '.png\'');
};

page.onLoadFinished = function(status) {
  if (status === 'success') {
    renderChart(data, id);
    return phantom.exit();
  } else {
    console.log('Connection failed.');
    return phantom.exit();
  }
};

page.onConsoleMessage = function(msg) {
  return console.log(msg);
};

page.viewportSize = {
  width: imgWidth,
  height: imgHeight
};

page.open('chart-markdown/' + type + '.html');
